### ISSUE TITLE
NetworkError on Mi Band 4

### ISSUE THREAD

**Issue by robertjohnpecayo23** [dj0001/miband3-selfie#2]
Upon scanning device, this shows up on logs:

Requesting Bluetooth Device...
Connecting to the device...
Argh! NetworkError: Connection failed for unknown reason.

Maybe have some error code for easier error fixing? I appreciate your work tho

**Comment by dj0001** [comment]
you use Mi Band 4
you use a webapp, which works only with Miband3 (I guess the [Demo](https://dj0001.github.io/miband3-selfie/))

Working with Miband4:
.11.20 [miband4-selfie](https://dj0001.github.io/miband3-selfie/miband4-selfie.html) (search handy)
.12.20[ Kiox2](https://dj0001.github.io/miband3-selfie/testki.html) and [HR2](https://dj0001.github.io/miband3-selfie/csvtocanvas2.htm) works with BLE Peripheral Simulatur on android, and with Miband 4 (Gadgetbridge must be connected)

enable 3rd party HR access in Gadgetbridge (or MiFit)
start an Activity on the band
first connect Gadgetbridge (maybe MiFit also works, untested)
then connect web app in chrome android (click Scan button)
